NewsPortal/NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('posts/', include('news.urls')),
    path('news/', include('news.urls')),
]

NewsPortal/news/urls.py
from django.urls import path
from . views import Posts, PostDetail, PostCreateView, PostSearch, PostUpdateView, PostDeleteView


urlpatterns = [
    path('', Posts.as_view(), name='news'),
    path('<int:pk>', PostDetail.as_view(), name='post'),
    path('search/', PostSearch.as_view(), name = 'search' ),
    path('add/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/edit', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    ]

NewsPortal/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    def update_rating(self):
        post_rating = Post.objects.filter(author=self).aggregate(
            Sum('rating'))['rating__sum']
        comment_rating = Comment.objects.filter(user=self.user).aggregate(
            Sum('rating'))['rating__sum']
        comment_rating_to_posts = Comment.objects.filter(
            post__author__user=self.user).aggregate(Sum('rating'))[
            'rating__sum']

        self.rating = ((post_rating * 3) + comment_rating +
                       comment_rating_to_posts)
        self.save()

class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete= models.CASCADE, verbose_name = "Автор")
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE, verbose_name="Категория")
    dateCreation = models.DateTimeField(auto_now_add=True,
                                        verbose_name="Дата создания новости")
    postCategory = models.ManyToManyField(Category, through='PostCategory', verbose_name="Тематика")
    title = models.CharField(max_length=128, verbose_name="Заголовок")
    text = models.TextField(verbose_name="Текст")
    rating = models.SmallIntegerField(default=0)
    def like(self):
        self.rating += 1
        self.save()
    def dislike(self):
        self.rating -= 1
        self.save()
    def preview(self):
        # return '{}…{}'.format(self.text[0..123],'...')
        return self.text[0:123] + '...'
    def __str__(self):
        return f'{self.title.title()}: {self.text}'
    def get_absolute_url(self):
        return f'/news/{self.id}'

class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)

class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)  # автоматически добавлять время создания поста
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPortal/news/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'categoryType', 'postCategory', 'author']

NewsPortal/accounts/views.py
from django.shortcuts import render

# Create your views here.

NewsPortal/news/views.py

from .models import Post, Comment, Category, PostCategory
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .filters import PostFilter
from .forms import PostForm
from django.contrib.auth.mixins import LoginRequiredMixin

from datetime import datetime
from django.shortcuts import render
from django.views import View  # импортируем простую вьюшку
from django.core.paginator import Paginator

class Posts(ListView):
    model = Post
    template_name = 'news.html'
    context_object_name = 'news'
    queryset = Post.objects.order_by('-dateCreation')
    paginate_by = 1
    form_class = PostForm

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.now()
        context['filter'] = PostFilter(self.request.GET,
                                          queryset=self.get_queryset())
        context['postCategories'] = Category.objects.all()
        context['form'] = PostForm()
        return context

class PostDetail(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.now()
        context['comment_list'] = Comment.objects.filter(commentPost=self.kwargs['pk'])

        return context

class PostSearch(ListView):
    model = Post
    template_name = 'search.html'
    context_object_name = 'news'
    queryset = Post.objects.all()  # Н

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[
            'time_now'] = datetime.now()
        context['filter'] = PostFilter(self.request.GET,
                                       queryset=self.get_queryset())
        return context

class PostCreateView(CreateView):
    template_name = 'post_create.html'
    form_class = PostForm

class PostUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'post_create.html'
    form_class = PostForm
    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)

class PostDeleteView(DeleteView):
    template_name = 'post_delete.html'
    queryset = Post.objects.all()
    success_url = '/news/'

NewsPortal/templates/allposts.html
{% extends 'flatpages/default.html' %}
{% block title %}
Posts
{% endblock title %}
{% block content %}
<h1>Все публикации</h1>
<h3>{{ time_now|date:'d M Y' }}, Всего публикаций: {{ posts|length }}</h3>
    <hr>
    {% if posts %}
        <table>
            <tr>
                <th>
                    Заголовок
                </th>
                <th>
                    Дата публикации
                </th>
                <th>
                    Категория
                </th>
                <th>
                    Автор
                </th>
                <th>
                    Текст
                </th>
            </tr>
        {% for post in posts %}
            <tr>
                <td>
                    {{ post.title }}
                </td>
                <td>
                    {{ post.dateCreation|date:'d M Y' }}
                </td>
                <td>
                    {{ post.categoryType }}
                </td>
                <td>
                    {{ post.author.authorUser.username }}
                </td>
                <td>
                    {{ post.text|truncatewords:20 }}
                </td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <h2>Публикаций нет!</h2>
    {% endif %}
{% endblock content %}

NewsPortal/templates/base.html
{% extends 'static/index.html' %}
{% load custom_tags %}
{% block title %}Новостной портал | страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}{% endblock title %}
{% block content %}{% for p in news %}
        <div class="card mx-1 mb-2" style="width:48%">
            <div class="card-header"><h5 class="text-center">{{ p.title }}</h5></div>
            <div class="card-body">{{ p.text|truncatechars:50 }}
    <a href="{% url 'post' p.pk %}" class="stretched-link text-secondary">    Читать далее</a>
            </div>
            <div class="card-footer">
        <p class="float-start"><i>Рейтинг:{{ p.rating }}</i></p>
        <p class="float-end"><i>{{ p.dateCreation|date:"j F Y" }}</i></p>
            </div>
        </div>

        {% empty %}
        <h4>Публикации не найдены</h4>
        {% endfor %}{% endblock %}

{% block search %}<div class="col-sm-2 bg-light p-3">
            <form action="" method="get">
       {{ filterset.form.as_p }}
            <input type="submit" value="Найти" /></form>
        </div>{% endblock search %}

{% block pagination %}
    <ul class="pagination pagination-sm justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}"><span aria-hidden="true">&laquo;</span></a></li>
    <li class="page-item"><a class="page-link" href="?{% url_replace page=1 %}">1</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link"><span aria-hidden="true">&laquo;</span></a></li>
       {% if page_obj.previous_page_number != 1 %}

    <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

    <li class="page-item active"><a class="page-link">{{ page_obj.number }}</a></li>

   {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a></li>
    {% if paginator.num_pages != page_obj.next_page_number %}
    <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a></li>
    {% endif %}
    {% endif %}

    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}"><span aria-hidden="true">&raquo;</span></a></li>
      {% else %}
    <li class="page-item disabled"><a class="page-link"><span aria-hidden="true">&raquo;</span></a></li>
    {% endif %}</ul>{% endblock pagination %}

NewsPortal/templates/news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %}
news
{% endblock title %}
{% block content %}
<h1>Все публикации</h1>
<h3>Сейчас {{ time_now|date:'d F Y / H:i' }},
    <!-- {{ time_now|time:"H:i" }}-->
    Всего публикаций: {{ news|length }} {{ Posts.queryset.count}} </h3>
    <hr>
    {% if news %}
        <table align="center">
            <tr>
                <th>
                    Заголовок
                </th>
                <th>
                    Дата публикации
                </th>
                <th>
                    Категория
                </th>
                <th>
                    Автор
                </th>
                <th>
                    Текст
                </th>
            </tr>
        {% for post in news %}
            <tr>
                <td>
                    <a href="{% url 'post' post.id %}"><b>{{ post.title | censor }}</b></a>
                    <br><a href="{% url 'post_update' post.id %}"><i>Редактировать</i></a>
                    <a href="{% url 'post_delete' post.id %}"><i> Удалить </i></a>
                </td>
                <td>
                    {{ post.dateCreation|date:'d M Y / H:i' }}
                </td>
                <td>
                    {{ post.categoryType }}
                </td>
                <td>
                    {{ post.author.authorUser.username }}
                </td>
                <td>
                    {{ post.text | censor | truncatechars:51 }}
                </td>
            </tr>
        {% endfor %}
        </table>
<p><a href="{% url 'post_create' %}">Добавить новую публикацию</a> <br>
    <a href="{% url 'search' %}">Поиск по публикациям</a> <br>
        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a href="?page=1">First</a>
                <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a>{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">>>></a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

        {% endif %}
    {% else %}
        <h2>Публикаций нет!</h2>
    {% endif %}
{% endblock content %}

NewsPortal/templates/post.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %}
{{ post.id }} || {{ post.title }}
{% endblock title %}
{% block content %}
{% if post %}
<h1>{{ post.title | censor }}</h1>
<i>ID = {{ post.id }}</i>
<h3>Дата публикации: {{ post.dateCreation|date:'d F Y' }}. Время публикации: {{ time_now|time:"H:i" }}</h3>
<h3>Категория: {{ post.categoryType }} - {{ post.get_categoryType_display }}</h3>
<h3>Тематика:
{% for c in post.postCategory.all %}
{{c.name}},
{% endfor %}
</h3>
<h3>Автор: {{ post.author.authorUser.username }}</h3>
<p>{{post.text | censor}}</p>
<br><a href="{% url 'post_update' post.id %}"><i>Редактировать</i></a>
                    <a href="{% url 'post_delete' post.id %}"><i> Удалить </i></a>
<hr>
<h3>Комментарии: </h3>
<p><strong>Сейчас {{ time_now|date:'d F Y / H:i' }},
    <!-- {{ time_now|time:"H:i" }}-->
    Всего комментариев: {{ comment_list|length }}</strong></p>
    <hr>
    {% if comment_list %}
        {% for comment in comment_list %}
              <div>
                  <h4>Автор: {{ comment.commentUser.username }}</h4>
                  <p>Опубликовано: {{ comment.dateCreation|date:'d M Y / H:i' }}</p>
                  <p>{{ comment.text | censor | truncatechars:51 }}</p>
                  <p>Рейтинг: {{ comment.rating }}</p>
                  <hr>
              </div>
        {% endfor %}
    {% else %}
        <h2>Комментариев нет!</h2>
    {% endif %}
{% else %}
        <h2>Такая публикация не существует!</h2>
{% endif %}
{% endblock content %}

NewsPortal/templates/post_create.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %}Добавление записи{% endblock title %}
{% block content %}
<div class="container px-5">
<div class="card">
  <div class="card-header">
  </div>
  <div class="card-body mx-3">
    <h5 class="card-title text-center"><b>Post creating</b></h5>
    <p class="card-text"><form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
          {% comment %}
          {% endcomment %}
      <button type="submit" class="btn btn-success mt-1">Готово!</button>
      </form>
    </p>
  </div>
</div>
  </div>{% endblock content %}

NewsPortal/templates/post_delete.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %}
{{ post.id }} || {{ post.title }}
{% endblock title %}
{% block content %}
{% if post %}
<h1>{{ post.title | censor }}</h1>
<h2>Вы действительно хотите удалить данную публикацию?</h2>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="подтвердить"></form>
{% endif %}
<i>ID = {{ post.id }}</i>
<h3>Дата публикации: {{ post.dateCreation|date:'d F Y' }}. Время публикации: {{ time_now|time:"H:i" }}</h3>
<h3>Категория: {{ post.categoryType }} - {{ post.get_categoryType_display }}</h3>
<h3>Автор: {{ post.author.authorUser.username }}</h3>
<p>{{post.text | censor}}</p>
<hr>
<h3>Комментарии: </h3>
<p><strong>Сейчас {{ time_now|date:'d F Y / H:i' }},
    Всего комментариев: {{ comment_list|length }}</strong></p>
    <hr>
    {% if comment_list %}
        {% for comment in comment_list %}
              <div>
                  <h4>Автор: {{ comment.commentUser.username }}</h4>
                  <p>Опубликовано: {{ comment.dateCreation|date:'d M Y / H:i' }}</p>
                  <p>{{ comment.text | censor | truncatechars:51 }}</p>
                  <p>Рейтинг: {{ comment.rating }}</p>
                  <hr>
              </div>
        {% endfor %}
    {% else %}
        <h2>Комментариев нет!</h2>
    {% endif %}
{% endblock content %}

NewsPortal/templates/search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %}
news
{% endblock title %}
{% block content %}
<h1>Все публикации</h1>
<h3>Сейчас {{ time_now|date:'d F Y / H:i' }},
    Всего публикаций: {{ news|length }}</h3>
    <hr>
    {% if news %}
<form method="GET">
    {{ filter.form }}
    <input type="submit" value="Найти">
</form>
        <table>
            <tr>
                <th>
                    Заголовок
                </th>
                <th>
                    Дата публикации
                </th>
                <th>
                    Категория
                </th>
                <th>
                    Автор
                </th>
                <th>
                    Текст
                </th>
            </tr>
        {% for post in filter.qs %}
            <tr>
                <td>
                    <a href="{% url 'post' post.id %}"><b>{{ post.title | censor }}</b></a>
                    <br><a href="{% url 'post_update' post.id %}"><i>Редактировать</i></a>
                    <a href="{% url 'post_delete' post.id %}"><i> Удалить </i></a>
                </td>
                <td>
                    {{ post.dateCreation|date:'d M Y / H:i' }}
                </td>
                <td>
                    {{ post.categoryType }}
                </td>
                <td>
                    {{ post.author.authorUser.username }}
                </td>
                <td>
                    {{ post.text | censor | truncatechars:51 }}
                </td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <h2>Публикаций нет!</h2>
    {% endif %}
{% endblock content %}